version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: raxo
      MONGO_INITDB_ROOT_PASSWORD: jdHAKZ!172Lks

  backend:
    build: ./backEnd/
    restart: always
    ports: 
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - FRONTEND_URI=http://localhost:3000
      - MONGODB_CONNSTRING=mongodb://raxo:jdHAKZ!172Lks@mongo:27017/ctfDB?authSource=admin
      - SESSION_SECRET=djbh28Y879U292dklkdjjd
    volumes:
      - ./backEnd/assets:/server/assets
    depends_on:
      - mongo

  frontend:
    build: ./frontEnd/
    restart: always
    ports: 
      - '3000:3000'
    environment:
      - REACT_APP_SERVER_URI=http://localhost:3001
      - REACT_APP_CTF_NAME=TEST_CTF
      - GENERATE_SOURCEMAP=false